export const iconOptions = [
  { value: "Home", label: "Home" },
  { value: "Hospital", label: "Hospital" },
  { value: "School", label: "Escola" },
  { value: "Store", label: "Loja" },
  { value: "Bank", label: "Banco" },
  { value: "Office", label: "Escritório" },
  { value: "Factory", label: "Fábrica" },
  { value: "Library", label: "Biblioteca" },
  { value: "Museum", label: "Museu" },
  { value: "Map", label: "Mapa" },
  { value: "MapPin", label: "Ponto no Mapa" },
  { value: "Airport", label: "Aeroporto" },
  { value: "AmusementPark", label: "Parque de Diversões" },
  { value: "Aquarium", label: "Aquário" },
  { value: "ArtGallery", label: "Galeria de Arte" },
  { value: "Atm", label: "Caixa Eletrônico" },
  { value: "Bakery", label: "Padaria" },
  { value: "Bar", label: "Bar" },
  { value: "BeautySalon", label: "Salão de Beleza" },
  { value: "BicycleStore", label: "Loja de Bicicletas" },
  { value: "BookStore", label: "Livraria" },
  { value: "BowlingAlley", label: "Pista de Boliche" },
  { value: "BusStation", label: "Estação de Ônibus" },
  { value: "Cafe", label: "Cafeteria" },
  { value: "Campground", label: "Área de Camping" },
  { value: "CarDealer", label: "Concessionária" },
  { value: "CarRental", label: "Aluguel de Carros" },
  { value: "CarRepair", label: "Oficina" },
  { value: "CarWash", label: "Lava Rápido" },
  { value: "Casino", label: "Cassino" },
  { value: "Cemetery", label: "Cemitério" },
  { value: "Church", label: "Igreja" },
  { value: "CityHall", label: "Prefeitura" },
  { value: "ClothingStore", label: "Loja de Roupas" },
  { value: "ConvenienceStore", label: "Loja de Conveniência" },
  { value: "Courthouse", label: "Tribunal" },
  { value: "Dentist", label: "Dentista" },
  { value: "DepartmentStore", label: "Loja de Departamento" },
  { value: "Doctor", label: "Médico" },
  { value: "Electrician", label: "Eletricista" },
  { value: "ElectronicsStore", label: "Loja de Eletrônicos" },
  { value: "Embassy", label: "Embaixada" },
  { value: "FireStation", label: "Bombeiros" },
  { value: "Florist", label: "Florista" },
  { value: "FuneralHome", label: "Funerária" },
  { value: "FurnitureStore", label: "Loja de Móveis" },
  { value: "GasStation", label: "Posto de Gasolina" },
  { value: "Gym", label: "Academia" },
  { value: "HairSalon", label: "Cabeleireiro" },
  { value: "HardwareStore", label: "Loja de Ferragens" },
  { value: "HinduTemple", label: "Templo Hindu" },
  { value: "HomeGoodsStore", label: "Casa & Decoração" },
  { value: "InsuranceAgency", label: "Agência de Seguros" },
  { value: "JewelryStore", label: "Joalheria" },
  { value: "Laundry", label: "Lavanderia" },
  { value: "Lawyer", label: "Advogado" },
  { value: "LiquorStore", label: "Loja de Bebidas" },
  { value: "LocalGovernmentOffice", label: "Órgão Público" },
  { value: "Locksmith", label: "Chaveiro" },
  { value: "Lodging", label: "Hospedagem" },
  { value: "MealDelivery", label: "Entrega de Comida" },
  { value: "MealTakeaway", label: "Comida para Viagem" },
  { value: "Mosque", label: "Mesquita" },
  { value: "MovieRental", label: "Locadora" },
  { value: "MovieTheater", label: "Cinema" },
  { value: "MovingCompany", label: "Empresa de Mudanças" },
  { value: "NightClub", label: "Boate" },
  { value: "Painter", label: "Pintor" },
  { value: "Park", label: "Parque" },
  { value: "Parking", label: "Estacionamento" },
  { value: "PetStore", label: "Pet Shop" },
  { value: "Pharmacy", label: "Farmácia" },
  { value: "Physiotherapist", label: "Fisioterapeuta" },
  { value: "Plumber", label: "Encanador" },
  { value: "Police", label: "Delegacia" },
  { value: "PostOffice", label: "Correios" },
  { value: "RealEstateAgency", label: "Imobiliária" },
  { value: "Restaurant", label: "Restaurante" },
  { value: "RoofingContractor", label: "Telhadista" },
  { value: "RvPark", label: "Área de Trailers" },
  { value: "SecondarySchool", label: "Ensino Médio" },
  { value: "ShoeStore", label: "Sapataria" },
  { value: "ShoppingMall", label: "Shopping" },
  { value: "Spa", label: "Spa" },
  { value: "Stadium", label: "Estádio" },
  { value: "Storage", label: "Depósito" },
  { value: "SubwayStation", label: "Metrô" },
  { value: "Supermarket", label: "Supermercado" },
  { value: "Synagogue", label: "Sinagoga" },
];
